<?php
        //Database connection parameters
        $MYSQL_SERVER = "localhost";
        $MYSQL_USER = "exscitech";
        $MYSQL_PASSWORD = "CuuuRZqjxqzH3QpN";
        $MYSQL_DB = "exscitech_web";
        $MYSQL_FORUM_DB = "exscitech_forum";

        //Flashcard Data Directories
        $PNG_DIR = "/var/www/ExSciTecH/public_html/data/PNG/";
        $SDF_DIR = "/var/www/ExSciTecH/public_html/data/SDF/";
        
        date_default_timezone_set('EST');
?>